### PR TITLE
Converted most of the old python code, prob broken.

### PR DESCRIPTION
**Pull request by pnadon**

### CODE REVIEW

**Comment by pnadon** [comment]
I have absolutely no idea if any of this works. On the upside, it all fits in a single file of ~80 lines (including whitespace and comments).

I expect minor fixes, not entire rewrites.

**Comment by pnadon** [comment]
Also, I revamped the way we store data on the server, I made a quick python script which transforms the csvs in json (easier to work with using javascript). Then instead of using pandas etc to filter, we just use standard javascript map/filter/reduce and stuff.

**Comment by pnadon** [comment]
Should probably add tests and link them to github ci/cd...

**Comment by pnadon** [comment]
Still need to build endpoints: https://github.com/oscjaimes/rand-stock/blob/e875342daeb8100785871a7c2a5ef4a6ba93dc5a/server.py

Not sure how much the server side stuff will change when using nextjs.

**Review by oscj — APPROVED** [review]
LGTM

**Pull request merged**
